language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"
matrix:
    allow_failures:
        - php: "hhvm"
notifications:
  irc:
    channels:
        - "chat.freenode.net#dokuwiki"
    on_success: change
    on_failure: change
script: cd _test && phpunit --verbose --stderr
